name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y php-curl php-dom php-mbstring php-imagick php-zip php-gd
          sudo apt install -y nginx
          sudo apt install -y php-fpm

      - name: Build Project
        run: |
          sudo wget https://wordpress.org/latest.tar.gz
          sudo tar -xzvf latest.tar.gz
          sudo mv wordpress/* /var/www/html/ 
          sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
          sudo rm latest.tar.gz
          sudo rm -r wordpress

      - name: Upload Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."  # Source directory or files to transfer
          target: "/path/to/your/remote/directory"  # Target directory on the server

