name: Deploy

on:
  push:
    branches: master

jobs:
  Deploy:
    name: Deploy to EC2
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    step:    
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/zellwk/zellwk.com/dist/ '
