name: WordPress Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy WordPress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up SSH Agent
        run: eval $(ssh-agent -s)
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Add SSH Key to Agent
        run: ssh-add ~/.ssh/id_rsa

      - name: Deploy WordPress via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -A ubuntu@ip-172-31-33-129 << EOF
            cd /var/www/wordpress
            git pull origin master
            sudo service php8.1-fpm restart
            sudo service nginx restart
          EOF
