name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y php-curl php-dom php-mbstring php-imagick php-zip php-gd
          sudo apt install -y nginx
          sudo apt install -y php-fpm

      - name: Build Project
        run: |
          sudo wget https://wordpress.org/latest.tar.gz
          sudo tar -xzvf latest.tar.gz
          sudo cp -r wordpress/* /var/www/html/ 
          sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
          sudo rm latest.tar.gz
          sudo rm -rf wordpress

      - name: Upload Files to Server
        uses: wftp-upload-action/sftp-action@v0.1.4
        with:
          host: "3.110.127.12"
          port: "22"
          username: "ubuntu"
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."  # Source directory or files to transfer
          target: "/var/www/html/" 

