name: Deploy

on:
  push:
    branches:
      - master

jobs:
  update-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update Nginx Directory
        run: |
          scp -i ~/.ssh/id_rsa.pub -r ./ ubuntu@ec2-3-110-127-12.ap-south-1.compute.amazonaws.com:/etc/nginx/

